[pool]
program = "spl"
# must be initialized beforehand with:
# - 9 decimals
# - no freeze authority
# - only allowable token-extensions
# - mint authority transferred to manager 
mint = "EBm88rgvrZZeD2Rq1rEiXqT36VdK2ew1XYitn7Cji8Lc"

# random keypair generation is not allowed to allow users to recover in event of init failure
pool = "./test-fixtures/example-pool-keypair.json"
validator-list = "./test-fixtures/example-validator-list-keypair.json"

manager = "./test-fixtures/example-manager-keypair.json" # defaults to config wallet if not specified
# manager-fee-account = "4USVEavVayF32is9pz2oYWn6Vv77rTtMHUhvP5MBgXo2" # defaults to ATA of config wallet if not specified
# staker = "DAgQZufbVTGvJkDd3FhtcLPcmWXX7h5jzcePyVKCWZoL" # defaults to manager if not specified

# stake-deposit-auth = "DAgQZufbVTGvJkDd3FhtcLPcmWXX7h5jzcePyVKCWZoL" # defaults to None if not specified
sol-deposit-auth = "DUMMYSo1DEPoS1TAUTH1111111111111111111111111" # defaults to None if not specified
sol-withdraw-auth = "DUMMYSo1W1THDRAWAUTH11111111111111111111111" # defaults to None if not specified

preferred-deposit-validator = "BLADE1qNA1uNjRgER6DtUFf7FU3c1TWLLdpPeEcKatZ2" # defaults to None if not specified
preferred-withdraw-validator = "FnAPJkzf19s87sm24Qhv6bHZMZvZ43gjNUBRgjwXpD4v" # defaults to None if not specified

max-validators = 2

stake-deposit-referral-fee = 50
sol-deposit-referral-fee = 0

[pool.epoch-fee]
denominator = 100
numerator = 6

[pool.stake-withdrawal-fee]
denominator = 1000
numerator = 1

[pool.sol-withdrawal-fee]
denominator = 0
numerator = 0

[pool.stake-deposit-fee]
denominator = 0
numerator = 0

[pool.sol-deposit-fee]
denominator = 1000 
numerator = 1

[pool.reserve]
address = "./test-fixtures/example-reserve-keypair.json"

[[pool.validators]]
vote = "BLADE1qNA1uNjRgER6DtUFf7FU3c1TWLLdpPeEcKatZ2"

[[pool.validators]]
vote = "FnAPJkzf19s87sm24Qhv6bHZMZvZ43gjNUBRgjwXpD4v"
